server {
    listen 127.0.0.1:8080;
    server_name cgi_test;
    client_max_body_size 100K;
    
    location / {
	    client_max_body_size 100;
        root ./www;
        index index.html;
        methods GET;
        autoindex off;
    }
    
    location /cgi-bin/ {
        root ./www/cgi-bin/;
        methods GET POST;
        cgi_enable on;
        cgi_path /usr/bin/python3;
        cgi_ext .py;
    }
}