server {
    listen 127.0.0.1:8080;
    server_name local;

    client_max_body_size 5M;

    error_page 404 /errors/404.html;
    error_page 403 /errors/403.html;
    error_page 413 /errors/413.html;

    location / {
        root ./www;
        index index.html;
        methods GET;
        autoindex off;
    }

    location /files {
        root ./www/files;
        autoindex on;
        methods GET;
    }

    location /go {
        return 301 https://example.org/;
        methods GET;
    }

    location /upload {
        methods POST;
        upload_enable on;
        upload_store ./www/uploads;
    }

    location /del {
        methods DELETE;
        upload_enable on;
        upload_store ./www/uploads;
    }
}
