server {
    listen 127.0.0.1:8080;
    server_name localhost;
    client_max_body_size 100K;
    
    error_page 404 /errors/404.html;
    error_page 403 /errors/403.html;
    error_page 413 /errors/413.html;
    error_page 500 /errors/500.html;
    
    location / {
        root ./www2;
        index index.html;
        methods GET POST DELETE;
        autoindex on;
    }
    
    location /uploads/ {
        root ./www2/uploads;
        methods GET POST DELETE;
        autoindex on;
    }
    
    location /cgi-bin/ {
        root ./www2/cgi-bin/;
        methods GET POST;
        cgi_enable on;
        cgi_path /usr/bin/python3;
        cgi_ext .py;
    }
    
    location /forbidden {
        return 403;
    }
    
    location /redirect {
        return 301 /;
    }
}

server {
    listen 127.0.0.1:8081;
    server_name localhost;
    
    location / {
        root ./www2;
        index index.html;
        methods GET;
    }
}

server {
    listen 127.0.0.1:8082;
    server_name localhost;
    
    location / {
        root ./www2;
        index index.html;
        methods GET POST;
    }
}