server {
    listen 127.0.0.1:9000;
    server_name web8080;

    client_max_body_size 25M;

    error_page 404 /errors/404.html;
    error_page 413 /errors/413.html;

    location / {
        root ./www;
        index index.html;
        autoindex off;
        methods GET;
    }

    location /uploads {
        root ./uploads;
        autoindex on;
        methods GET POST DELETE;
        upload_enable on;
        upload_store ./uploads;
    }
}

server {
    listen 127.0.0.1:8081;
    server_name web8081;

    client_max_body_size 1G;

    error_page 404 /errors/404.html;
    error_page 413 /errors/413.html;

    location / {
        root ./www;
        index index.html;
        autoindex off;
        methods GET;
    }

    location /uploads {
        root ./www;
        autoindex on;
        methods GET POST DELETE;
        upload_enable on;
        upload_store ./www/uploads;
    }

    location /cgi-bin {
        root ./www/cgi-bin;
        methods GET POST;
        cgi_enable on;
        cgi_extension .py;
        cgi_path /usr/bin/python3;
    }
}
